/**
 * Riesa Wines API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface QuoteItemOutput { 
    wine_name: string;
    wine_denomination: string | null;
    quantity: number;
}

