/**
 * Riesa Wines API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuoteItemOutput } from './quoteItemOutput';


export interface QuoteRequestOutput { 
    id: number;
    customer_type: string;
    email: string;
    notes: string | null;
    address: string | null;
    city: string | null;
    province: string | null;
    postal_code: string | null;
    country: string | null;
    full_address: string;
    items: Array<QuoteItemOutput>;
    created_at: string;
}

