/**
 * Riesa Wines API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuoteItemInput } from './quoteItemInput';


export interface QuoteRequestInput { 
    customer_type: string;
    email: string;
    notes?: string | null;
    address: string;
    city: string;
    province: string;
    postal_code: string;
    country?: string;
    items: Array<QuoteItemInput>;
}

