/**
 * Riesa Wines API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WineSchema { 
    id: number;
    name: string;
    denomination?: string | null;
    grape?: string | null;
    altitude?: string | null;
    soil_composition?: string | null;
    cultivation_method?: string | null;
    harvest?: string | null;
    vinification?: string | null;
    aging?: string | null;
    description: string;
    alcohol?: string | null;
    serving_temperature?: string | null;
    aging_potential?: string | null;
    format?: string | null;
    closure?: string | null;
    image_url: string;
    background: string;
    text_color?: string | null;
}

